name: CI Pipeline

on:
  push:
    branches: [main, simplificado]  # Runs when code is pushed to main or simplificado
  pull_request:
    branches: [main]  # Runs on PRs targeting main

jobs:
  build_and_test:
    name: Build and Test Application
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches the latest code from the repository

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Uses Eclipse Temurin (OpenJDK)
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build and Run Tests
        run: mvn clean install  # Compiles, runs tests, and packages the app

      - name: Verify Application Runs
        run: mvn spring-boot:run & sleep 10 && curl --fail http://localhost:8080/api/books || (echo "Application failed to start" && exit 1)
